apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-jupyter-on-k8s-01
spec:
  title: "Jupyter on Kubernetes #1"
  description: A workshop exploring deployment of Jupyter notebooks locally and to Kubernetes
  url: https://github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-01
  content:
    files: github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-01
  duration: 45m
  session:
    namespaces:
      budget: large
    applications:
      console:
        enabled: true
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
    ingresses:
    - name: local-8888
      port: 8888
