apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-jupyter-on-k8s-01
spec:
  title: "Jupyter on Kubernetes #1"
  description: A workshop exploring deployment of Jupyter notebooks locally and to Kubernetes.
  workshop:
    files:
    - image:
        url: $(image_repository)/lab-jupyter-on-k8s-01-files:latest
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: large
      security:
        policy: baseline
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    ingresses:
    - name: local-8888
      port: 8888
